global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'exporter_script'
  #   static_configs:
  #     - targets: ['host.docker.internal:9092']

  - job_name: 'my_exporter'
    static_configs:
      - targets: ['my_exporter:9092']
